server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user_routh                    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8081          #匹配后提供服务的路由地址
          uri: lb://UserManager           #匹配后提供服务的路由地址
          predicates:
            - Path=/**         # 断言，路径相匹配的进行路由
#
#        - id: ticket_routh                #路由的ID，没有固定规则但要求唯一，建议配合服务名
##          uri: http://localhost:8082          #匹配后提供服务的路由地址
#          uri: lb://TicketManager            #匹配后提供服务的路由地址
#          predicates:
#            - Path=/**                  # 断言，路径相匹配的进行路由
        - id: pay_routh                #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8083          #匹配后提供服务的路由地址
          uri: lb://PayManager            #匹配后提供服务的路由地址
          predicates:
            - Path=/**            # 断言，路径相匹配的进行路由
#            - After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
#            - Cookie=username,sss
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: gateway.com
  client:           #服务提供者provider注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka,http://127.0.0.1:8200/eureka
    register-with-eureka: true
    fetch-registry: true



